---
  apache_service: httpd
  apache_daemon: httpd
  apache_daemon_path: /usr/sbin/
  apache_server_root: /etc/httpd
  apache_conf_path: /etc/httpd/conf.d
  src_app_filepath: ../../files/index.html
  dest_apache_app_filepath: /var/www/html/index.html

  apache_vhosts_version: "2.4"

  __apache_packages:
    - httpd
    - httpd-devel
    - mod_ssl
    - openssh

  apache_ports_configuration_items:
    - regexp: "^Listen "
      line: "Listen {{ apache_listen_port }}"
    - regexp: "^#?NameVirtualHost "
      line: "NameVirtualHost {{ apache_listen_ip }}:{{ apache_listen_port }}"
