---
  # Provision EC2 Instance
  - name: create EC2 security group
    ec2_group:
      name: "{{ SEC_GRP_NAME }}"
      description: Security Group for WebServer EC2 instance
      vpc_id: "{{ AWS_VPC_ID }}"
      region: "{{ AWS_REGION }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
        cidr_ip: 0.0.0.0/0
      register: instance_level_security

  - name: Launch the new EC2 Instance
    ec2:
      group: "{{ SEC_GRP_NAME }}"
      instance_type: "{{ EC2_INSTANCE_TYPE }}"
      image: "{{ IMAGE_ID }}"
      wait: yes
      wait_timeout: 500
      region: "{{ AWS_REGION }}"
      volumes:
        - device_name: "{{ AWS_EC2_DISK_DEVICE_NAME }}"
          volume_type: gp2
          volume_size: 10
          delete_on_termination: true
      monitoring: yes
      vpc_subnet_id: "{{ AWS_VPC_SUBNET_ID }}"
      assign_public_ip: yes
      key_name: ../../files/keypair_ansible.pem
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY}}"
      count: "{{ EC2_COUNT }}"
      register: ec2_instance_details

  - name: Display and store EC2 instnce id to variable
    debug: var=ec2_instance_details

  - name: Add the newly created EC2 instance(s) to the aws group
    lineinfile:
      dest: "../../hosts"
      regexp: "{{ item.public_ip }}"
      insertafter: "[aws]"
      line: "{{ item.public_ip }}"
    with_items: "{{ ec2.instances }}"
